kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: helloworld
  image: alpine
  commands:
  - pwd
  - echo helloThere
  when:
  branch:
  - master
  event:
  - push
  - pull-request

- name: send
  image: plugins/webhook
  settings:
    urls: http://879ebcbd.ngrok.io/
    content_type: application/json
    template: >
        "#### My Msg ..."
  debug: true
  branch:
  - auto
  event:
  - push
  - pull-request
